/**
 * Hand-written rather than generated by a plugin: the whole site is one HTML
 * file, one hashed bundle and one hashed stylesheet, so the entire caching
 * story fits in a page you can read, and there is no generated manifest to
 * fall out of step with the build.
 *
 * What this is for is launch speed on a phone with bad signal, not offline
 * use. Every event comes from Google, so with no network you get the app's own
 * sign-in or "couldn't load" screen rather than the browser's error page —
 * which is the honest outcome, and still better than a blank tab.
 *
 * Bump VERSION to throw away everything cached by an older worker.
 */
const VERSION = 'v1'
const SHELL = `shell-${VERSION}`
const ASSETS = `assets-${VERSION}`

/** Every navigation is answered from this one entry, whatever path was asked for. */
const SHELL_URL = '/index.html'

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(SHELL)
      .then((cache) => cache.add(new Request(SHELL_URL, { cache: 'reload' })))
      // A first visit that fails to precache is not worth failing the install
      // over: the next navigation caches the shell anyway.
      .catch(() => {})
      .then(() => self.skipWaiting())
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) =>
        Promise.all(names.filter((name) => name !== SHELL && name !== ASSETS).map((n) => caches.delete(n)))
      )
      .then(() => self.clients.claim())
  )
})

self.addEventListener('fetch', (event) => {
  const { request } = event
  if (request.method !== 'GET') return

  // Sign-in and the Calendar API are cross-origin. They must never be cached —
  // a stale event list is worse than no event list — and returning here leaves
  // them entirely to the browser rather than merely passing them through.
  if (new URL(request.url).origin !== self.location.origin) return

  event.respondWith(request.mode === 'navigate' ? navigate(request) : asset(request))
})

/**
 * Network first, so a deploy is picked up on the next launch. The cached copy
 * is the fallback, not the default: index.html names the hashed bundle, and
 * serving yesterday's copy would pin the app to yesterday's build.
 */
async function navigate(request) {
  const cache = await caches.open(SHELL)
  try {
    const response = await fetch(request)
    // Only a real page is worth keeping. A 404, or the login page a hotel wifi
    // portal answers with, would poison every later launch.
    if (response.ok) {
      await cache.put(SHELL_URL, response.clone())
      await prune(response.clone())
    }
    return response
  } catch (error) {
    return (await cache.match(SHELL_URL)) || Response.error()
  }
}

/**
 * Cache first, which is safe precisely because these URLs are content-hashed:
 * a changed file is a changed name, so a hit can never be stale.
 */
async function asset(request) {
  const hashed = new URL(request.url).pathname.startsWith('/assets/')
  if (!hashed) return fetch(request)

  const cache = await caches.open(ASSETS)
  const cached = await cache.match(request)
  if (cached) return cached

  const response = await fetch(request)
  if (response.ok) cache.put(request, response.clone())
  return response
}

/**
 * Hashed names never collide, so nothing here expires on its own: without this
 * the cache would keep a copy of the bundle from every deploy, forever. The
 * fresh page names the only files still wanted; the rest can go.
 */
async function prune(response) {
  const html = await response.text()
  const wanted = new Set(html.match(/\/assets\/[\w.-]+/g))
  if (!wanted.size) return

  const cache = await caches.open(ASSETS)
  const keys = await cache.keys()
  await Promise.all(
    keys.filter((key) => !wanted.has(new URL(key.url).pathname)).map((key) => cache.delete(key))
  )
}
